package com.ajisegiri.springbootDynamoDB.model;

import com.ajisegiri.springbootDynamoDB.converter.LocalDateConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import java.io.Serializable;
import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "customer")
public class Customer implements Serializable{

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String customerId;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private String contactNumber;
    @DynamoDBAttribute
    private Address address;
    @DynamoDBAttribute
    private CustomerDetails customerDetails;
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @DynamoDBAttribute
    private LocalDate creationDate;
}
